#!/bin/sh
set -e
(date -Iseconds; echo gopls) >> ~/date.txt
GOCACHE=/.cache/gocache
GOMODCACHE=/.cache/gomodcache
docker run --rm -i -u $(id -u):$(id -g) -e "GOCACHE=$GOCACHE" -e "GOFLAGS=$GOFLAGS" -w "$PWD" -v "$PWD:$PWD" -v "$PWD/.go/cache:/.cache" -v $PWD/bin/tools/gopls:/usr/local/bin/gopls golang:1.20-alpine gopls "$@"
